name: CI

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted]
    env:
        PROJECT_PATH: ".\\"
        BUILD_METHOD_WIN64: "BuildProject.BuildWindows64"
        BUILD_METHOD_WIN32: "BuildProject.BuildWindows32"
        gameName: "Plataformote"
        projectVersion: "Test"
    steps:
      - name: Build For Windows 64 bits
        run: Start-Process -Wait 'C:\Program Files\Unity\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PROJECT_PATH -executeMethod $env:BUILD_METHOD_WIN64 -quit"
      - name: Build For Windows 32 bits
        run: Start-Process -Wait 'C:\Program Files\Unity\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PROJECT_PATH -executeMethod $env:BUILD_METHOD_WIN32 -quit"

